# Generated by Django 4.2.3 on 2023-10-11 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_manager', '0003_remove_subscription_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liability',
            name='date',
            field=models.DateField(default=datetime.date(2023, 10, 11)),
        ),
    ]
